version: '3.8'
services:
  web:
    build: ./logic/web/
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./logic/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - postgres-db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=strive
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=students_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-db:
    driver: local